- hosts: util-final
  user: deployer
  become: true
  vars:
    password: $6$S2W38Fc2$8zDTu7rQtnfQmMukLnxsNR2qpwjaXiTbEIfiC7puk/MZQadaEMgFqhnEY1sGkwKT0EvioNAUREaB2txtgtLDb0
 
  tasks:
    - user: name=test3 password={{password}} shell="/bin/bash"
